### ISSUE TITLE
Group for future use

### ISSUE THREAD

**Issue by Heki2017** [nklerk/nl.nielsdeklerk.log#5]
Not an issue, but a request. Implementing ‘group’ would be great benefit. If logging could be grouped, debugging of scenarios, would be greatly improved, as the csv file imported in Excell can be easily filtered on the group. Anyway Niels, I am very happy with the app so far! Thanks for putting your time in.

**Comment by nklerk** [comment]
The backend has groups implemented. I’ll have a look at it. What do you think. Will a text field be enough or having a setting where you need to define groups first and then making them selectable in the flow cards?

**Comment by Heki2017** [comment]
Hi Niels,

Thanks for fast respons. In my opinion a text field is sufficient. I saw when downloading the CSV, that it was at that end already there :-)

Kind regards Hedzer

**Comment by nklerk** [comment]
I've just pushed an update:

**Comment by nklerk** [comment]
- Added API: get log feature. GET http://<HOST>/api/app/nl.nielsdeklerk.log/ to get all logging.
- Added new card to provide a group name for the logging.
- Added Limit of 2000 Logging entries. Newer log entries will remove the oldest.

**Comment by Heki2017** [comment]
Wow Niels, that is fast. Will check it out this weekend. Also the GET option is really great,

Kind regards Hedzer

**Comment by nklerk** [comment]
Ive submitted it as beta. After its being reviewed (usually happend wijting a week) i can publish it. But feel free to use the git version.

**Comment by Heki2017** [comment]
Thanks Niels, I understand I was a bit to greedy. Unfortunately I have no knowledge how to use the git version. I’l wait for the reviewed version, regs Hedzer

**Comment by Heki2017** [comment]
😀👍

**Comment by nklerk** [comment]
The changes are published in the Athom appstore as beta.

**Comment by Heki2017** [comment]
Hi Niels, top, it works great and also the option to get access on an endpoint is fantastic, kind regards Hedzer
