### ISSUE TITLE
Not compatible with v.2.0.0

### ISSUE THREAD

**Issue by mhoogenbosch** [nklerk/nl.nielsdeklerk.log#6]
When trying to install your app on my v2.0.0 RC4 version of Homey it reports a 'not compatible' state.

**Comment by nklerk** [comment]
The message is correct. Once I've updated the settings UI to work on v2 it will be solved. I'm working on multiple apps at the moment, so please bear with me.

**Comment by mhoogenbosch** [comment]
No worries, just didn't see it on the open issues list 👍

**Comment by nklerk** [comment]
The 2.0 version is now live.
