### ISSUE TITLE
Homey 2.0 variabelen

### ISSUE THREAD

**Issue by tonvos** [nklerk/nl.nielsdeklerk.log#7]
Hallo Niels,
Ik werk al een tijd met jou log app, ben er zeer te vrede mee.
Gisteren heb ik mijn homey upgraded naar versie 2.0.
Het valt mij nu op dat de inhoud van variabelen niet meer worden getoond.
Wat laat die nu zien in de log [null]!
Moet ik iets aanpassen of is het een bug?
Ik hoor graag van je.
Mvg Ton

**Comment by nklerk** [comment]
Ik zal het na kijken. Je bedoelt de inhoud van tags toch? Zou gewoon moeten werken. Dat is waar ik het juist zelf voor gebruik.

**Comment by tonvos** [comment]
Sorry Niels,
Het ligt niet aan jou app maar aan de app van BetterLogic!
De app BetterLogic moes nog geupdate worden, en wat niet automatisch ging.
Nu zie ik de BetterLogic variabelen wel in jou app.
Bedankt voor je snelle reactie en tot ziens.
